services:
  app:
    container_name: risk-manager
    image: risk-manager
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 80
    networks:
      - proxy

networks:
  proxy:
    external: true
